from __future__ import annotations

from django.core.management.base import BaseCommand
from django.db import transaction
from example.core.models import Author, Book


class Command(BaseCommand):
    help = "Reset database with demo data"

    @transaction.atomic
    def handle(self, *args: object, **options: object) -> None:
        Author.objects.all().delete()

        marcus = Author.objects.create(name="Marcus Aurelius")
        Book.objects.create(author=marcus, title="Meditations")

        jane = Author.objects.create(name="Jane Austen")
        Book.objects.create(author=jane, title="Sense and Sensibility")
        Book.objects.create(author=jane, title="Pride and Prejudice")
        Book.objects.create(author=jane, title="Mansfield Park")
        Book.objects.create(author=jane, title="Emma")
        Book.objects.create(author=jane, title="Northanger Abbey")
        Book.objects.create(author=jane, title="Persuasion")
        Book.objects.create(author=jane, title="Lady Susan")

        charles = Author.objects.create(name="Charles Dickens")
        Book.objects.create(author=charles, title="The Pickwick Papers")
        Book.objects.create(author=charles, title="Oliver Twist")
        Book.objects.create(author=charles, title="Nicholas Nickleby")
        Book.objects.create(author=charles, title="The Old Curiosity Shop")
        Book.objects.create(author=charles, title="Barnaby Rudge")
        Book.objects.create(author=charles, title="A Christmas Carol")
        Book.objects.create(author=charles, title="Martin Chuzzlewit")
        Book.objects.create(author=charles, title="The Chimes")
        Book.objects.create(author=charles, title="The Cricket on the Hearth")
        Book.objects.create(author=charles, title="The Battle of Life")
        Book.objects.create(author=charles, title="Dombey and Son")
        Book.objects.create(author=charles, title="The Haunted Man")
        Book.objects.create(author=charles, title="David Copperfield")
        Book.objects.create(author=charles, title="Bleak House")
        Book.objects.create(author=charles, title="Hard Times")
        Book.objects.create(author=charles, title="Little Dorrit")
        Book.objects.create(author=charles, title="A Tale of Two Cities")
        Book.objects.create(author=charles, title="Great Expectations")
        Book.objects.create(author=charles, title="Our Mutual Friend")
        Book.objects.create(author=charles, title="The Signal-Man")
        Book.objects.create(author=charles, title="Edwin Drood")

        will = Author.objects.create(name="William Shakespeare")
        Book.objects.create(author=will, title="The Tempest")
        Book.objects.create(author=will, title="The Two Gentlemen of Verona")
        Book.objects.create(author=will, title="The Merry Wives of Windsor")
        Book.objects.create(author=will, title="Measure for Measure")
        Book.objects.create(author=will, title="The Comedy of Errors")
        Book.objects.create(author=will, title="Much Ado About Nothing")
        Book.objects.create(author=will, title="Love's Labour's Lost")
        Book.objects.create(author=will, title="A Midsummer Night's Dream")
        Book.objects.create(author=will, title="The Merchant of Venice")
        Book.objects.create(author=will, title="As You Like It")
        Book.objects.create(author=will, title="The Taming of the Shrew")
        Book.objects.create(author=will, title="All's Well That Ends Well")
        Book.objects.create(author=will, title="Twelfth Night")
        Book.objects.create(author=will, title="The Winter's Tale")
        Book.objects.create(author=will, title="King John")
        Book.objects.create(author=will, title="Richard II")
        Book.objects.create(author=will, title="Henry IV, Part 1")
        Book.objects.create(author=will, title="Henry IV, Part 2")
        Book.objects.create(author=will, title="Henry V")
        Book.objects.create(author=will, title="Henry VI, Part 1")
        Book.objects.create(author=will, title="Henry VI, Part 2")
        Book.objects.create(author=will, title="Henry VI, Part 3")
        Book.objects.create(author=will, title="Richard III")
        Book.objects.create(author=will, title="Henry VIII")
        Book.objects.create(author=will, title="Troilus and Cressida")
        Book.objects.create(author=will, title="Coriolanus")
        Book.objects.create(author=will, title="Titus Andronicus")
        Book.objects.create(author=will, title="Romeo and Juliet")
        Book.objects.create(author=will, title="Timon of Athens")
        Book.objects.create(author=will, title="Julius Caesar")
        Book.objects.create(author=will, title="Macbeth")
        Book.objects.create(author=will, title="Hamlet")
        Book.objects.create(author=will, title="King Lear")
        Book.objects.create(author=will, title="Othello")
        Book.objects.create(author=will, title="Antony and Cleopatra")
        Book.objects.create(author=will, title="Cymbeline")

        agatha = Author.objects.create(name="Agatha Christie")
        Book.objects.create(author=agatha, title="The Mysterious Affair at Styles")
        Book.objects.create(author=agatha, title="The Secret Adversary")
        Book.objects.create(author=agatha, title="The Murder on the Links")
        Book.objects.create(author=agatha, title="The Man in the Brown Suit")
        Book.objects.create(author=agatha, title="The Secret of Chimneys")
        Book.objects.create(author=agatha, title="The Murder of Roger Ackroyd")
        Book.objects.create(author=agatha, title="The Big Four")
        Book.objects.create(author=agatha, title="The Mystery of the Blue Train")
        Book.objects.create(author=agatha, title="The Seven Dials Mystery")
        Book.objects.create(author=agatha, title="The Murder at the Vicarage")
        Book.objects.create(author=agatha, title="Giant's Bread")
        Book.objects.create(author=agatha, title="The Floating Admiral")
        Book.objects.create(author=agatha, title="The Sittaford Mystery")
        Book.objects.create(author=agatha, title="Peril at End House")
        Book.objects.create(author=agatha, title="Lord Edgware Dies")
        Book.objects.create(author=agatha, title="Murder on the Orient Express")
        Book.objects.create(author=agatha, title="Unfinished Portrait")
        Book.objects.create(author=agatha, title="Why Didn't They Ask Evans?")
        Book.objects.create(author=agatha, title="Three Act Tragedy")
        Book.objects.create(author=agatha, title="Death in the Clouds")
        Book.objects.create(author=agatha, title="The A.B.C. Murders")
        Book.objects.create(author=agatha, title="Murder in Mesopotamia")
        Book.objects.create(author=agatha, title="Cards on the Table")
        Book.objects.create(author=agatha, title="Dumb Witness")
        Book.objects.create(author=agatha, title="Death on the Nile")
        Book.objects.create(author=agatha, title="Appointment with Death")
        Book.objects.create(author=agatha, title="Hercule Poirot's Christmas")
        Book.objects.create(author=agatha, title="Murder Is Easy")
        Book.objects.create(author=agatha, title="Ten Little Indians")
        Book.objects.create(author=agatha, title="Sad Cypress")
        Book.objects.create(author=agatha, title="One, Two, Buckle My Shoe")
        Book.objects.create(author=agatha, title="Evil Under the Sun")
        Book.objects.create(author=agatha, title="N or M?")
        Book.objects.create(author=agatha, title="The Body in the Library")
        Book.objects.create(author=agatha, title="Five Little Pigs")
        Book.objects.create(author=agatha, title="The Moving Finger")
        Book.objects.create(author=agatha, title="Towards Zero")
        Book.objects.create(author=agatha, title="Absent in the Spring")
        Book.objects.create(author=agatha, title="Death Comes as the End")
        Book.objects.create(author=agatha, title="Sparkling Cyanide")
        Book.objects.create(author=agatha, title="The Hollow")
        Book.objects.create(author=agatha, title="Taken at the Flood")
        Book.objects.create(author=agatha, title="The Rose and the Yew Tree")
        Book.objects.create(author=agatha, title="Crooked House")
        Book.objects.create(author=agatha, title="A Murder Is Announced")
        Book.objects.create(author=agatha, title="They Came to Baghdad")
        Book.objects.create(author=agatha, title="Mrs McGinty's Dead")
        Book.objects.create(author=agatha, title="They Do It with Mirrors")
        Book.objects.create(author=agatha, title="A Daughter's a Daughter")
        Book.objects.create(author=agatha, title="After the Funeral")
        Book.objects.create(author=agatha, title="A Pocket Full of Rye")
        Book.objects.create(author=agatha, title="Destination Unknown")
        Book.objects.create(author=agatha, title="Hickory Dickory Dock")
        Book.objects.create(author=agatha, title="Dead Man's Folly")
        Book.objects.create(author=agatha, title="The Burden")
        Book.objects.create(author=agatha, title="4.50 from Paddington")
        Book.objects.create(author=agatha, title="Ordeal by Innocence")
        Book.objects.create(author=agatha, title="Cat Among the Pigeons")
        Book.objects.create(author=agatha, title="The Pale Horse")
        Book.objects.create(author=agatha, title="The Mirror Crack'd from Side to Side")
        Book.objects.create(author=agatha, title="The Clocks")
        Book.objects.create(author=agatha, title="A Caribbean Mystery")
        Book.objects.create(author=agatha, title="At Bertram's Hotel")
        Book.objects.create(author=agatha, title="Third Girl")
        Book.objects.create(author=agatha, title="Endless Night")
        Book.objects.create(author=agatha, title="By the Pricking of My Thumbs")
        Book.objects.create(author=agatha, title="Hallowe'en Party")
        Book.objects.create(author=agatha, title="Passenger to Frankfurt")
        Book.objects.create(author=agatha, title="Nemesis")
        Book.objects.create(author=agatha, title="Elephants Can Remember")
        Book.objects.create(author=agatha, title="Postern of Fate")
        Book.objects.create(author=agatha, title="Curtain")
        Book.objects.create(author=agatha, title="Sleeping Murder")
        Book.objects.create(
            author=agatha, title="Hercule Poirot and the Greenshore Folly"
        )

        print("👍 Demo data created")
